---

- hosts: 192.168.58.135

  tasks:
   - name: Installation du serveur Apapche et PHP
     yum:
      name: "{{ item }}"
      state: present
     loop:
       - httpd 
       - php


   - name: Arret du service nginx
     systemd:
      name: nginx
      state: stopped

   - name: Démmarage du serveur apache
     systemd:
      name: httpd
      state: started
 
   - name: Suppression du fichier index.html
     file:
      path: /var/www/html/index.html
      state: absent
   - name: Copie du php info
     copy:
      src: index.php
      dest: /var/www/html/
